export default [
  { dsd: 'chakra-factory', chakra: '/website/pages/docs/features/chakra-factory.mdx' },
  { dsd: 'button', chakra: '/website/pages/docs/form/button.mdx' },
  { dsd: 'checkbox', chakra: '/website/pages/docs/form/checkbox.mdx' },
  { dsd: 'editable', chakra: '/website/pages/docs/form/editable.mdx' },
  { dsd: 'form-control', chakra: '/website/pages/docs/form/form-control.mdx' },
  { dsd: 'icon-button', chakra: '/website/pages/docs/form/icon-button.mdx' },
  { dsd: 'input', chakra: '/website/pages/docs/form/input.mdx' },
  { dsd: 'number-input', chakra: '/website/pages/docs/form/number-input.mdx' },
  { dsd: 'pin-input', chakra: '/website/pages/docs/form/pin-input.mdx' },
  { dsd: 'radio', chakra: '/website/pages/docs/form/radio.mdx' },
  { dsd: 'select', chakra: '/website/pages/docs/form/select.mdx' },
  { dsd: 'slider', chakra: '/website/pages/docs/form/slider.mdx' },
  { dsd: 'switch', chakra: '/website/pages/docs/form/switch.mdx' },
  { dsd: 'textarea', chakra: '/website/pages/docs/form/textarea.mdx' },

  { dsd: 'badge', chakra: '/website/pages/docs/data-display/badge.mdx' },
  { dsd: 'code', chakra: '/website/pages/docs/data-display/code.mdx' },
  { dsd: 'divider', chakra: '/website/pages/docs/data-display/divider.mdx' },
  { dsd: 'kbd', chakra: '/website/pages/docs/data-display/kbd.mdx' },
  { dsd: 'list', chakra: '/website/pages/docs/data-display/list.mdx' },
  { dsd: 'stat', chakra: '/website/pages/docs/data-display/stat.mdx' },
  { dsd: 'table', chakra: '/website/pages/docs/data-display/table.mdx' },
  { dsd: 'tag', chakra: '/website/pages/docs/data-display/tag.mdx' },

  { dsd: 'alert', chakra: '/website/pages/docs/feedback/alert.mdx' },
  { dsd: 'circular-progress', chakra: '/website/pages/docs/feedback/circular-progress.mdx' },
  { dsd: 'progress', chakra: '/website/pages/docs/feedback/progress.mdx' },
  { dsd: 'skeleton', chakra: '/website/pages/docs/feedback/skeleton.mdx' },
  { dsd: 'spinner', chakra: '/website/pages/docs/feedback/spinner.mdx' },
  { dsd: 'toast', chakra: '/website/pages/docs/feedback/toast.mdx' },

  { dsd: 'aspect-ratio', chakra: '/website/pages/docs/layout/aspect-ratio.mdx' },
  { dsd: 'box', chakra: '/website/pages/docs/layout/box.mdx' },
  { dsd: 'center', chakra: '/website/pages/docs/layout/center.mdx' },
  { dsd: 'container', chakra: '/website/pages/docs/layout/container.mdx' },
  { dsd: 'flex', chakra: '/website/pages/docs/layout/flex.mdx' },
  { dsd: 'grid', chakra: '/website/pages/docs/layout/grid.mdx' },
  { dsd: 'simple-grid', chakra: '/website/pages/docs/layout/simple-grid.mdx' },
  { dsd: 'stack', chakra: '/website/pages/docs/layout/stack.mdx' },
  { dsd: 'wrap', chakra: '/website/pages/docs/layout/wrap.mdx' },

  { dsd: 'avatar', chakra: '/website/pages/docs/media-and-icons/avatar.mdx' },
  { dsd: 'icon', chakra: '/website/pages/docs/media-and-icons/icon.mdx' },
  { dsd: 'image', chakra: '/website/pages/docs/media-and-icons/image.mdx' },

  { dsd: 'breadcrumb', chakra: '/website/pages/docs/navigation/breadcrumb.mdx' },
  { dsd: 'link', chakra: '/website/pages/docs/navigation/link.mdx' },
  { dsd: 'link-overlay', chakra: '/website/pages/docs/navigation/link-overlay.mdx' },

  { dsd: 'accordion', chakra: '/website/pages/docs/disclosure/accordion.mdx' },
  { dsd: 'tabs', chakra: '/website/pages/docs/disclosure/tabs.mdx' },
  { dsd: 'visually-hidden', chakra: '/website/pages/docs/disclosure/visually-hidden.mdx' },

  { dsd: 'alert-dialog', chakra: '/website/pages/docs/overlay/alert-dialog.mdx' },
  { dsd: 'drawer', chakra: '/website/pages/docs/overlay/drawer.mdx' },
  { dsd: 'menu', chakra: '/website/pages/docs/overlay/menu.mdx' },
  { dsd: 'modal', chakra: '/website/pages/docs/overlay/modal.mdx' },
  { dsd: 'popover', chakra: '/website/pages/docs/overlay/popover.mdx' },
  { dsd: 'tooltip', chakra: '/website/pages/docs/overlay/tooltip.mdx' },
];